"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var TASK_STATUS_CODE;
(function (TASK_STATUS_CODE) {
    TASK_STATUS_CODE[TASK_STATUS_CODE["ALL"] = 0] = "ALL";
    TASK_STATUS_CODE[TASK_STATUS_CODE["UNASSIGNED"] = 1] = "UNASSIGNED";
    TASK_STATUS_CODE[TASK_STATUS_CODE["ASSIGNED"] = 2] = "ASSIGNED";
    TASK_STATUS_CODE[TASK_STATUS_CODE["REVIEWING"] = 3] = "REVIEWING";
    TASK_STATUS_CODE[TASK_STATUS_CODE["COMPLETED"] = 4] = "COMPLETED";
})(TASK_STATUS_CODE = exports.TASK_STATUS_CODE || (exports.TASK_STATUS_CODE = {}));
