export enum ROUTE_NAME {
  ENTRY = "entry",
  SIGNIN = "signin",
  LOGIN = "login",
  HEPLER = "helper",
  TASK = "task",
  TASK_LISTING = "taskListing",
  TRANSACTION = "transaction",
  TRANSACTION_LISTING = "transactionListing",
  DEFRAY = "defray",
  PROFILE = "profile",
  MANAGEMENT_ENTRY = "managementEntry",
  MANAGEMENT_SIGNIN = "managementSignin",
  MANAGEMENT_LOGIN = "managementLogin",
  MANAGEMENT_TASK = "managementTask",
  MANAGEMENT_TASK_LISTING = "managementTaskListing",
  MANAGEMENT_USER_TASK = "managementUserTask",
  MANAGEMENT_USER_TASK_LISTING = "managementUserTaskListing",
  MANAGEMENT_TRANSACTION = "managementTransaction",
  MANAGEMENT_TRANSACTION_LISTING = "managementTransactionListing",
  MANAGEMENT_USER = "managementUser",
  MANAGEMENT_USER_LISTING = "managementUserListing",
  MANAGEMENT_PROFILE = "managementProfile",
  PAGE_NOT_FOUND = "pageNotFound"
}

export enum ROUTE_TITLE {
  ENTRY = "首页",
  SIGNIN = "注册",
  LOGIN = "登录",
  HEPLER = "新手帮助",
  TASK = "任务明细",
  TASK_LISTING = "任务清单",
  TRANSACTION = "交易明细",
  TRANSACTION_LISTING = "交易清单",
  DEFRAY = "提现",
  PROFILE = "我的",
  MANAGEMENT_ENTRY = "管理端首页",
  MANAGEMENT_SIGNIN = "管理端注册",
  MANAGEMENT_LOGIN = "管理端登录",
  MANAGEMENT_TASK = "管理端任务明细",
  MANAGEMENT_TASK_LISTING = "管理端任务清单",
  MANAGEMENT_USER_TASK = "管理端用户接受任务细明",
  MANAGEMENT_USER_TASK_LISTING = "管理端用户接受任务清单",
  MANAGEMENT_TRANSACTION = "管理端交易明细",
  MANAGEMENT_TRANSACTION_LISTING = "管理端交易清单",
  MANAGEMENT_USER = "管理端用户明细",
  MANAGEMENT_USER_LISTING = "管理端用户列表",
  MANAGEMENT_PROFILE = "管理端我的",
  PAGE_NOT_FOUND = "页面未找到"
}

export enum ROUTE_PATH {
  ENTRY = "/",
  SIGNIN = "/signin",
  LOGIN = "/login",
  HEPLER = "/hepler",
  TASK = "/task/:id",
  TASK_LISTING = "/task-listing",
  TRANSACTION = "/transaction/:id",
  TRANSACTION_LISTING = "/transaction-listing",
  DEFRAY = "/defray",
  PROFILE = "/profile",
  MANAGEMENT_ENTRY = "/management",
  MANAGEMENT_SIGNIN = "/management/signin",
  MANAGEMENT_LOGIN = "/management/login",
  MANAGEMENT_TASK = "/management/task",
  MANAGEMENT_TASK_LISTING = "/management/task-listing",
  MANAGEMENT_USER_TASK = "/management/user-task/:id",
  MANAGEMENT_USER_TASK_LISTING = "/management/user-task-listing",
  MANAGEMENT_TRANSACTION = "/management/transaction/:id",
  MANAGEMENT_TRANSACTION_LISTING = "/management/transaction-listing",
  MANAGEMENT_USER = "/management/user/:id",
  MANAGEMENT_USER_LISTING = "/management/user-listing",
  MANAGEMENT_PROFILE = "/management/profile",
  PAGE_NOT_FOUND = "*"
}
