export enum COLOR {
  MAIN_BACKGROUND = "#F1F4F7",
  ITEM_BACKGROUND = "#FFFFFF",
  ITEM_SHADOW = "#FAFAFC",
  FONT_COLOR = "#284B75",
  FONT_CONTEXT_COLOR = "#000000",
  FONT_ACTIVE_COLOR = "#FFFFFF",
  ASSIGNED = "#14B3E2",
  REVIEWING = "#ECB414",
  COMPLETED = "#27Af2B"
}
