"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var USER_ROLE_CODE;
(function (USER_ROLE_CODE) {
    USER_ROLE_CODE[USER_ROLE_CODE["CONSUMER"] = 0] = "CONSUMER";
    USER_ROLE_CODE[USER_ROLE_CODE["CONSUMER_VIP"] = 1] = "CONSUMER_VIP";
    USER_ROLE_CODE[USER_ROLE_CODE["CUSTOMER"] = 2] = "CUSTOMER";
    USER_ROLE_CODE[USER_ROLE_CODE["CUSTOMER_ADMIN"] = 3] = "CUSTOMER_ADMIN";
    USER_ROLE_CODE[USER_ROLE_CODE["SUPER_ADMIN"] = 4] = "SUPER_ADMIN";
})(USER_ROLE_CODE = exports.USER_ROLE_CODE || (exports.USER_ROLE_CODE = {}));
var USER_ROLE_LEVEL_CODE;
(function (USER_ROLE_LEVEL_CODE) {
    USER_ROLE_LEVEL_CODE[USER_ROLE_LEVEL_CODE["VIP1"] = 1] = "VIP1";
    USER_ROLE_LEVEL_CODE[USER_ROLE_LEVEL_CODE["VIP2"] = 2] = "VIP2";
    USER_ROLE_LEVEL_CODE[USER_ROLE_LEVEL_CODE["VIP3"] = 3] = "VIP3";
    USER_ROLE_LEVEL_CODE[USER_ROLE_LEVEL_CODE["VIP4"] = 4] = "VIP4";
    USER_ROLE_LEVEL_CODE[USER_ROLE_LEVEL_CODE["VIP5"] = 5] = "VIP5";
})(USER_ROLE_LEVEL_CODE = exports.USER_ROLE_LEVEL_CODE || (exports.USER_ROLE_LEVEL_CODE = {}));
var USER_STATUS_CODE;
(function (USER_STATUS_CODE) {
    USER_STATUS_CODE[USER_STATUS_CODE["INACTIVE"] = 0] = "INACTIVE";
    USER_STATUS_CODE[USER_STATUS_CODE["LOGOUT"] = 1] = "LOGOUT";
    USER_STATUS_CODE[USER_STATUS_CODE["ACTIVE"] = 2] = "ACTIVE";
})(USER_STATUS_CODE = exports.USER_STATUS_CODE || (exports.USER_STATUS_CODE = {}));
