"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var USER_ROLE_CODE;
(function (USER_ROLE_CODE) {
    USER_ROLE_CODE[USER_ROLE_CODE["CONSUMER"] = 0] = "CONSUMER";
    USER_ROLE_CODE[USER_ROLE_CODE["CONSUMER_VIP"] = 1] = "CONSUMER_VIP";
    USER_ROLE_CODE[USER_ROLE_CODE["CUSTOMER"] = 2] = "CUSTOMER";
    USER_ROLE_CODE[USER_ROLE_CODE["CUSTOMER_ADMIN"] = 3] = "CUSTOMER_ADMIN";
    USER_ROLE_CODE[USER_ROLE_CODE["SUPER_ADMIN"] = 4] = "SUPER_ADMIN";
})(USER_ROLE_CODE = exports.USER_ROLE_CODE || (exports.USER_ROLE_CODE = {}));
var USER_ROLE_LEVEL_CODE;
(function (USER_ROLE_LEVEL_CODE) {
    USER_ROLE_LEVEL_CODE[USER_ROLE_LEVEL_CODE["VIP1"] = 1] = "VIP1";
    USER_ROLE_LEVEL_CODE[USER_ROLE_LEVEL_CODE["VIP2"] = 2] = "VIP2";
    USER_ROLE_LEVEL_CODE[USER_ROLE_LEVEL_CODE["VIP3"] = 3] = "VIP3";
    USER_ROLE_LEVEL_CODE[USER_ROLE_LEVEL_CODE["VIP4"] = 4] = "VIP4";
    USER_ROLE_LEVEL_CODE[USER_ROLE_LEVEL_CODE["VIP5"] = 5] = "VIP5";
})(USER_ROLE_LEVEL_CODE = exports.USER_ROLE_LEVEL_CODE || (exports.USER_ROLE_LEVEL_CODE = {}));
var USER_STATUS_CODE;
(function (USER_STATUS_CODE) {
    USER_STATUS_CODE[USER_STATUS_CODE["INACTIVE"] = 0] = "INACTIVE";
    USER_STATUS_CODE[USER_STATUS_CODE["LOGOUT"] = 1] = "LOGOUT";
    USER_STATUS_CODE[USER_STATUS_CODE["ACTIVE"] = 2] = "ACTIVE";
})(USER_STATUS_CODE = exports.USER_STATUS_CODE || (exports.USER_STATUS_CODE = {}));
var USER_ROLE_NAME;
(function (USER_ROLE_NAME) {
    USER_ROLE_NAME["CONSUMER"] = "\u666E\u901A\u7528\u6237";
    USER_ROLE_NAME["CONSUMER_VIP"] = "\u4F1A\u5458\u7528\u6237";
    USER_ROLE_NAME["CUSTOMER"] = "\u4EFB\u52A1\u53D1\u5E03\u5458";
    USER_ROLE_NAME["CUSTOMER_ADMIN"] = "\u4EFB\u52A1\u53D1\u5E03\u5458\u7BA1\u7406\u5458";
    USER_ROLE_NAME["SUPER_ADMIN"] = "\u8D85\u7EA7\u7BA1\u7406\u5458";
})(USER_ROLE_NAME = exports.USER_ROLE_NAME || (exports.USER_ROLE_NAME = {}));
var USER_ROLE_LEVEL_NAME;
(function (USER_ROLE_LEVEL_NAME) {
    USER_ROLE_LEVEL_NAME["VIP1"] = "VIP1";
    USER_ROLE_LEVEL_NAME["VIP2"] = "VIP2";
    USER_ROLE_LEVEL_NAME["VIP3"] = "VIP3";
    USER_ROLE_LEVEL_NAME["VIP4"] = "VIP4";
    USER_ROLE_LEVEL_NAME["VIP5"] = "VIP5";
})(USER_ROLE_LEVEL_NAME = exports.USER_ROLE_LEVEL_NAME || (exports.USER_ROLE_LEVEL_NAME = {}));
var USER_STATUS_NAME;
(function (USER_STATUS_NAME) {
    USER_STATUS_NAME["INACTIVE"] = "\u672A\u6FC0\u6D3B";
    USER_STATUS_NAME["LOGOUT"] = "\u767B\u51FA";
    USER_STATUS_NAME["ACTIVE"] = "\u5728\u7EBF";
})(USER_STATUS_NAME = exports.USER_STATUS_NAME || (exports.USER_STATUS_NAME = {}));
