import { DATE_TYPE_CODE } from "../../../types/common/date";
import {
  ORDER_STATUS_CODE,
  ORDER_TYPE_CODE
} from "../../../types/common/order";
import { DATE_TYPE_NAME, ORDER_STATUS_NAME, ORDER_TYPE_NAME } from "../enum";

export const orderTypeConfig = {
  [ORDER_TYPE_CODE.DEFAULT]: ORDER_TYPE_NAME.DEFAULT,
  [ORDER_TYPE_CODE.AMOUNT]: ORDER_TYPE_NAME.AMOUNT,
  [ORDER_TYPE_CODE.START_DATE]: ORDER_TYPE_NAME.START_DATE,
  [ORDER_TYPE_CODE.END_DATE]: ORDER_TYPE_NAME.END_DATE,
  [ORDER_TYPE_CODE.SUBMIT_DATE]: ORDER_TYPE_NAME.SUBMIT_DATE,
  [ORDER_TYPE_CODE.RESULT_DATE]: ORDER_TYPE_NAME.RESULT_DATE,
  [ORDER_TYPE_CODE.SIGNIN_DATE]: ORDER_TYPE_NAME.SIGNIN_DATE,
  [ORDER_TYPE_CODE.LOGIN_DATE]: ORDER_TYPE_NAME.LOGIN_DATE,
  [ORDER_TYPE_CODE.LOGOUT_DATE]: ORDER_TYPE_NAME.LOGOUT_DATE,
  [ORDER_TYPE_CODE.ASSIGN_DATE]: ORDER_TYPE_NAME.ASSIGN_DATE,
  [ORDER_TYPE_CODE.UPLOAD_DATE]: ORDER_TYPE_NAME.UPLOAD_DATE,
  [ORDER_TYPE_CODE.REVIEW_DATE]: ORDER_TYPE_NAME.REVIEW_DATE
};

export const orderStatusConfig = {
  [ORDER_STATUS_CODE.ASC]: ORDER_STATUS_NAME.ASC,
  [ORDER_STATUS_CODE.DESC]: ORDER_STATUS_NAME.DESC
};

export const dateTypeConfig = {
  [DATE_TYPE_CODE.START_DATE]: DATE_TYPE_NAME.START_DATE,
  [DATE_TYPE_CODE.END_DATE]: DATE_TYPE_NAME.END_DATE,
  [DATE_TYPE_CODE.SUBMIT_DATE]: DATE_TYPE_NAME.SUBMIT_DATE,
  [DATE_TYPE_CODE.RESULT_DATE]: DATE_TYPE_NAME.RESULT_DATE,
  [DATE_TYPE_CODE.SIGNIN_DATE]: DATE_TYPE_NAME.SIGNIN_DATE,
  [DATE_TYPE_CODE.LOGIN_DATE]: DATE_TYPE_NAME.LOGIN_DATE,
  [DATE_TYPE_CODE.LOGOUT_DATE]: DATE_TYPE_NAME.LOGOUT_DATE,
  [DATE_TYPE_CODE.ASSIGN_DATE]: DATE_TYPE_NAME.ASSIGN_DATE,
  [DATE_TYPE_CODE.UPLOAD_DATE]: DATE_TYPE_NAME.UPLOAD_DATE,
  [DATE_TYPE_CODE.REVIEW_DATE]: DATE_TYPE_NAME.REVIEW_DATE
};
