"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var TRANSACTION_STATUS_CODE;
(function (TRANSACTION_STATUS_CODE) {
    TRANSACTION_STATUS_CODE[TRANSACTION_STATUS_CODE["CANCEL"] = 0] = "CANCEL";
    TRANSACTION_STATUS_CODE[TRANSACTION_STATUS_CODE["SUCCESS"] = 1] = "SUCCESS";
    TRANSACTION_STATUS_CODE[TRANSACTION_STATUS_CODE["PENDING"] = 2] = "PENDING";
    TRANSACTION_STATUS_CODE[TRANSACTION_STATUS_CODE["FAIL"] = 3] = "FAIL";
})(TRANSACTION_STATUS_CODE = exports.TRANSACTION_STATUS_CODE || (exports.TRANSACTION_STATUS_CODE = {}));
var TRANSACTION_TYPE_CODE;
(function (TRANSACTION_TYPE_CODE) {
    TRANSACTION_TYPE_CODE[TRANSACTION_TYPE_CODE["RECHARGE"] = 1] = "RECHARGE";
    TRANSACTION_TYPE_CODE[TRANSACTION_TYPE_CODE["WITHDRAW"] = 2] = "WITHDRAW";
    TRANSACTION_TYPE_CODE[TRANSACTION_TYPE_CODE["REWARD"] = 3] = "REWARD";
    TRANSACTION_TYPE_CODE[TRANSACTION_TYPE_CODE["DIVIDEND"] = 4] = "DIVIDEND";
})(TRANSACTION_TYPE_CODE = exports.TRANSACTION_TYPE_CODE || (exports.TRANSACTION_TYPE_CODE = {}));
