"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var DATE_TYPE_CODE;
(function (DATE_TYPE_CODE) {
    DATE_TYPE_CODE[DATE_TYPE_CODE["START_DATE"] = 0] = "START_DATE";
    DATE_TYPE_CODE[DATE_TYPE_CODE["END_DATE"] = 1] = "END_DATE";
    DATE_TYPE_CODE[DATE_TYPE_CODE["SUBMIT_DATE"] = 2] = "SUBMIT_DATE";
    DATE_TYPE_CODE[DATE_TYPE_CODE["RESULT_DATE"] = 3] = "RESULT_DATE";
    DATE_TYPE_CODE[DATE_TYPE_CODE["SIGNIN_DATE"] = 4] = "SIGNIN_DATE";
    DATE_TYPE_CODE[DATE_TYPE_CODE["LOGIN_DATE"] = 5] = "LOGIN_DATE";
    DATE_TYPE_CODE[DATE_TYPE_CODE["LOGOUT_DATE"] = 6] = "LOGOUT_DATE";
    DATE_TYPE_CODE[DATE_TYPE_CODE["ASSIGN_DATE"] = 7] = "ASSIGN_DATE";
    DATE_TYPE_CODE[DATE_TYPE_CODE["UPLOAD_DATE"] = 8] = "UPLOAD_DATE";
    DATE_TYPE_CODE[DATE_TYPE_CODE["REVIEW_DATE"] = 9] = "REVIEW_DATE";
})(DATE_TYPE_CODE = exports.DATE_TYPE_CODE || (exports.DATE_TYPE_CODE = {}));
