"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var ORDER_TYPE_CODE;
(function (ORDER_TYPE_CODE) {
    ORDER_TYPE_CODE[ORDER_TYPE_CODE["DEFAULT"] = 0] = "DEFAULT";
    ORDER_TYPE_CODE[ORDER_TYPE_CODE["AMOUNT"] = 1] = "AMOUNT";
    ORDER_TYPE_CODE[ORDER_TYPE_CODE["START_DATE"] = 2] = "START_DATE";
    ORDER_TYPE_CODE[ORDER_TYPE_CODE["END_DATE"] = 3] = "END_DATE";
    ORDER_TYPE_CODE[ORDER_TYPE_CODE["SUBMIT_DATE"] = 4] = "SUBMIT_DATE";
    ORDER_TYPE_CODE[ORDER_TYPE_CODE["RESULT_DATE"] = 5] = "RESULT_DATE";
    ORDER_TYPE_CODE[ORDER_TYPE_CODE["SIGNIN_DATE"] = 6] = "SIGNIN_DATE";
    ORDER_TYPE_CODE[ORDER_TYPE_CODE["LOGIN_DATE"] = 7] = "LOGIN_DATE";
    ORDER_TYPE_CODE[ORDER_TYPE_CODE["LOGOUT_DATE"] = 8] = "LOGOUT_DATE";
    ORDER_TYPE_CODE[ORDER_TYPE_CODE["ASSIGN_DATE"] = 9] = "ASSIGN_DATE";
    ORDER_TYPE_CODE[ORDER_TYPE_CODE["UPLOAD_DATE"] = 10] = "UPLOAD_DATE";
    ORDER_TYPE_CODE[ORDER_TYPE_CODE["REVIEW_DATE"] = 11] = "REVIEW_DATE";
})(ORDER_TYPE_CODE = exports.ORDER_TYPE_CODE || (exports.ORDER_TYPE_CODE = {}));
var ORDER_STATUS_CODE;
(function (ORDER_STATUS_CODE) {
    ORDER_STATUS_CODE[ORDER_STATUS_CODE["ASC"] = 0] = "ASC";
    ORDER_STATUS_CODE[ORDER_STATUS_CODE["DESC"] = 1] = "DESC";
})(ORDER_STATUS_CODE = exports.ORDER_STATUS_CODE || (exports.ORDER_STATUS_CODE = {}));
var ORDER_TYPE_NAME;
(function (ORDER_TYPE_NAME) {
    ORDER_TYPE_NAME["DEFAULT"] = "id";
    ORDER_TYPE_NAME["AMOUNT"] = "amount";
    ORDER_TYPE_NAME["START_DATE"] = "startDate";
    ORDER_TYPE_NAME["END_DATE"] = "endDate";
    ORDER_TYPE_NAME["SUBMIT_DATE"] = "submitDate";
    ORDER_TYPE_NAME["RESULT_DATE"] = "resultDate";
    ORDER_TYPE_NAME["SIGNIN_DATE"] = "signInDate";
    ORDER_TYPE_NAME["LOGIN_DATE"] = "loginDate";
    ORDER_TYPE_NAME["LOGOUT_DATE"] = "logoutDate";
    ORDER_TYPE_NAME["ASSIGN_DATE"] = "assignDate";
    ORDER_TYPE_NAME["UPLOAD_DATE"] = "uploadDate";
    ORDER_TYPE_NAME["REVIEW_DATE"] = "reviewDate";
})(ORDER_TYPE_NAME = exports.ORDER_TYPE_NAME || (exports.ORDER_TYPE_NAME = {}));
var ORDER_STATUS_NAME;
(function (ORDER_STATUS_NAME) {
    ORDER_STATUS_NAME["ASC"] = "asc";
    ORDER_STATUS_NAME["DESC"] = "desc";
})(ORDER_STATUS_NAME = exports.ORDER_STATUS_NAME || (exports.ORDER_STATUS_NAME = {}));
