"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var ORDER_TYPE_CODE;
(function (ORDER_TYPE_CODE) {
    ORDER_TYPE_CODE[ORDER_TYPE_CODE["DEFAULT"] = 0] = "DEFAULT";
    ORDER_TYPE_CODE[ORDER_TYPE_CODE["AMOUNT"] = 1] = "AMOUNT";
    ORDER_TYPE_CODE[ORDER_TYPE_CODE["START_DATE"] = 2] = "START_DATE";
    ORDER_TYPE_CODE[ORDER_TYPE_CODE["END_DATE"] = 3] = "END_DATE";
    ORDER_TYPE_CODE[ORDER_TYPE_CODE["SUBMIT_DATE"] = 4] = "SUBMIT_DATE";
    ORDER_TYPE_CODE[ORDER_TYPE_CODE["RESULT_DATE"] = 5] = "RESULT_DATE";
    ORDER_TYPE_CODE[ORDER_TYPE_CODE["SIGNIN_DATE"] = 6] = "SIGNIN_DATE";
    ORDER_TYPE_CODE[ORDER_TYPE_CODE["LOGIN_DATE"] = 7] = "LOGIN_DATE";
    ORDER_TYPE_CODE[ORDER_TYPE_CODE["LOGOUT_DATE"] = 8] = "LOGOUT_DATE";
    ORDER_TYPE_CODE[ORDER_TYPE_CODE["ASSIGN_DATE"] = 9] = "ASSIGN_DATE";
    ORDER_TYPE_CODE[ORDER_TYPE_CODE["UPLOAD_DATE"] = 10] = "UPLOAD_DATE";
    ORDER_TYPE_CODE[ORDER_TYPE_CODE["REVIEW_DATE"] = 11] = "REVIEW_DATE";
})(ORDER_TYPE_CODE = exports.ORDER_TYPE_CODE || (exports.ORDER_TYPE_CODE = {}));
var ORDER_STATUS_CODE;
(function (ORDER_STATUS_CODE) {
    ORDER_STATUS_CODE[ORDER_STATUS_CODE["ASC"] = 0] = "ASC";
    ORDER_STATUS_CODE[ORDER_STATUS_CODE["DESC"] = 1] = "DESC";
})(ORDER_STATUS_CODE = exports.ORDER_STATUS_CODE || (exports.ORDER_STATUS_CODE = {}));
