"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var PLATFORM_CODE;
(function (PLATFORM_CODE) {
    PLATFORM_CODE[PLATFORM_CODE["DEFAULT"] = 0] = "DEFAULT";
    PLATFORM_CODE[PLATFORM_CODE["DOUYIN"] = 1] = "DOUYIN";
    PLATFORM_CODE[PLATFORM_CODE["KUAISHOU"] = 2] = "KUAISHOU";
    PLATFORM_CODE[PLATFORM_CODE["WEIBO"] = 3] = "WEIBO";
    PLATFORM_CODE[PLATFORM_CODE["WEISHI"] = 4] = "WEISHI";
    PLATFORM_CODE[PLATFORM_CODE["XIGUA"] = 5] = "XIGUA";
    PLATFORM_CODE[PLATFORM_CODE["TAOBAO"] = 6] = "TAOBAO";
    PLATFORM_CODE[PLATFORM_CODE["FACEBOOK"] = 7] = "FACEBOOK";
})(PLATFORM_CODE = exports.PLATFORM_CODE || (exports.PLATFORM_CODE = {}));
